name: Build and Push Jellyfin
on:
  push:
    branches:
      - "master"
    paths:
      - "jellyfin/Dockerfile"
      - ".github/workflows/build-and-push-jellyfin.yaml"
  workflow_dispatch: {}

env:
  JELLYFIN_VERSION: "10.9.0"
  JELLYFIN_FFMPEG_VERSION: "6.0.1-6"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:jellyfin"
          push: true
          tags: "infinitesoul/jellyfin:${{ env.JELLYFIN_VERSION }}-ffmpeg${{ env.JELLYFIN_FFMPEG_VERSION }}"
          platforms: linux/amd64,linux/arm64
          build-args: |
            "JELLYFIN_VERSION=${{ env.JELLYFIN_VERSION }}"
            "JELLYFIN_FFMPEG_VERSION=${{ env.JELLYFIN_FFMPEG_VERSION }}"
