name: Build and Push Jellyfin
on:
  push:
    branches:
      - "master"
    paths:
      - "jellyfin/Dockerfile"
  workflow_dispatch: {}

env:
  JELLYFIN_VERSION: "10.8.13"
  JELLYFIN_FFMPEG_VERSION: "6.0-8"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:jellyfin"
          push: true
          tags: "infinitesoul/jellyfin:${{ env.JELLYFIN_VERSION }}-ffmpeg${{ env.JELLYFIN_FFMPEG_VERSION }}"
          build-args:
            JELLYFIN_VERSION: ${{ env.JELLYFIN_VERSION }}
            JELLYFIN_FFMPEG_VERSION: ${{ env.JELLYFIN_FFMPEG_VERSION }}